services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build:
      context: ./server
    depends_on:
      - mongodb
    ports:
      - "11000:11000"
    environment:
      MONGO_USERNAME: user
      MONGO_PASSWORD: password
      MONGO_DATABASE: admin
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      HTTP_PORT: 11000

  frontend:
    build:
      context: ./client
    ports:
      - "80:8080"
    volumes:
      - "./frontendConfig:/app/src/app/cfg"

networks:
  net:
    internal: true